# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd332f06034af4a26f2eb2946dff2493c2870e3dfb81320ff12946fe6dceb0eb77668030f097911483ac627576af553d990db7c2d469f644ce6479bbd0127090

test:
  secret_key_base: 49c95f277e09082a19f1bbb556900dc496981c579fd231649672e787fa2409620671b589420fd2a20a648e35c9e44b7761fa8876ea7c7ae380a22cdd2c901507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
